version: '2'

services:
  short:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      HOST: '0.0.0.0'
      MONGO_URL: 'mongodb://mongo:27017'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
